### ISSUE TITLE
Running backend without connection configured throws an error

### ISSUE THREAD

**Issue by samb-vt** [IQEngine/IQEngine#431]
```run-api
Running FastAPI on port 5000...
INFO:     Started server process [12793]
INFO:     Waiting for application startup.
Starting from MongoDB 4.0.23 there isn't a generic Linux version of MongoDB
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<sync() done, defined at /home/sam/IQEngine/api/database/datasource_repo.py:60> exception=ClientAuthenticationError('Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:05ecb159-b01e-007d-3002-c83a24000000\nTime:2023-08-06T01:05:09.5187348Z\nErrorCode:AuthenticationFailed\nauthenticationerrordetail:Signature fields not well formed.')>
Traceback (most recent call last):
  File "/home/sam/IQEngine/api/database/datasource_repo.py", line 68, in sync
    async for metadata in metadatas:
  File "/home/sam/IQEngine/api/blob/azure_client.py", line 96, in get_metadata_files
    async for blob in container_client.list_blobs():
  File "/home/sam/.local/lib/python3.10/site-packages/azure/core/async_paging.py", line 142, in __anext__
    return await self.__anext__()
  File "/home/sam/.local/lib/python3.10/site-packages/azure/core/async_paging.py", line 145, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/sam/.local/lib/python3.10/site-packages/azure/core/async_paging.py", line 94, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/sam/.local/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 90, in _get_next_cb
    process_storage_error(error)
  File "/home/sam/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:05ecb159-b01e-007d-3002-c83a24000000
Time:2023-08-06T01:05:09.5187348Z
ErrorCode:AuthenticationFailed
authenticationerrordetail:Signature fields not well formed.
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:05ecb159-b01e-007d-3002-c83a24000000
Time:2023-08-06T01:05:09.5187348Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>
```

**Comment by samb-vt** [comment]
Actually the backend is still running, but there are no recordings listed. I also have a read-only SAS token which might be the issue.

**Comment by samb-vt** [comment]
Figured out the problem; had to do with the SAS token being expired.
